version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - mysql
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7.31
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - final:/var/lib/mysql/
volumes:
  final:
    driver: local
